### ISSUE TITLE
Bug in Bresenham's line algorithm (two of the octants)

### ISSUE THREAD

**Issue by byronwasti** [jamwaffles/embedded-graphics#11]
There seems to be a weird issue when drawing lines in two of the octants (the 4th and the 7th). 

Here is a plotting in Python from the output line values when trying to draw lines in a circle.
![figure_1](https://user-images.githubusercontent.com/5985936/38343239-b0637b6c-3850-11e8-846f-8c12fb75705f.png)

**Comment by jamwaffles** [comment]
Thanks for investigating this! I haven't done much testing with the line drawing algo; just that it can draw a triangle. I'll fix as soon as I can. PRs welcome ;)
