### ISSUE TITLE
Publish simulator as a crate for use in examples

### ISSUE THREAD

**Issue by rfuest** [jamwaffles/embedded-graphics#122]
It would be nice to be able to use the simulator in examples for other projects. Would it be possible to publish the simulator as a crate?

**Comment by jamwaffles** [comment]
Makes sense to me. I'll figure out a public API when I've got some energy back 😅

**Comment by rfuest** [comment]
Ok, great. And sorry for spamming the issues so shortly after a release :wink:.

**Comment by jamwaffles** [comment]
It's not a problem! I want to make this crate as decent as possible, and early feedback is great for that. Please keep it coming 😁

**Comment by jamwaffles** [comment]
[Published](https://crates.io/crates/embedded-graphics-simulator)!
