### ISSUE TITLE
Investigate and fix non-multiple-of-4 BMP image widths

### ISSUE THREAD

**Issue by jamwaffles** [jamwaffles/embedded-graphics#136]
As per https://github.com/jamwaffles/embedded-graphics/pull/127#discussion_r299813724, this needs investigating and fixing if possible.

Thanks to @evq for reporting this!

**Comment by rfuest** [comment]
I did some initial tests on supporting more of the new color types and some additional BMP/TGA variants. The new code should also fix this bug.

**Comment by jamwaffles** [comment]
Sweet, thanks for that! Will you have something to PR at some point? I'm eager to make the image story in e-g more full-featured.

**Comment by rfuest** [comment]
Yes, I will open a PR. I'm not sure when I get time to work on it, but maybe sometime next week.
