### ISSUE TITLE
Text macro names

### ISSUE THREAD

**Issue by rfuest** [jamwaffles/embedded-graphics#140]
Since e-g 0.5.1 all primitive macros are prefixed with `eg`. Maybe the text macros should also be prefixed for consistency.

**Comment by jamwaffles** [comment]
`egtext_6x8` feels like a bit of a mouthful to me. The docs clearly list the macros used, and the only reason the `eg` prefix was added was to prevent collisions with the builtin `line!()` debug macro (see #129). I don't think there's enough wrong with the current naming to change the text macros, so I'm going to close this issue. I'm happy to reopen this if naming confusion becomes a point of confusion among users.
