### ISSUE TITLE
Circles without stroke are drawn incorrectly

### ISSUE THREAD

**Issue by rfuest** [jamwaffles/embedded-graphics#143]
The stroke on circles is applied from the outside edge of the circle inwards. This means that a circle with only fill set should render the same way as one with stroke and fill set to the same color.

## Code
```rust
display.draw(egcircle!(
    (10, 16),
    3,
    fill = Some(Rgb888::RED)
));

display.draw(egcircle!(
    (22, 16),
    3,
    fill = Some(Rgb888::GREEN),
    stroke = Some(Rgb888::GREEN)
));
```

## Display
![circles](https://user-images.githubusercontent.com/226123/61818999-62398980-ae52-11e9-898b-098d8bf05918.png)

**Comment by jamwaffles** [comment]
Good catch, and thanks for the test case.

**Comment by rfuest** [comment]
There still seems to be a problem with this for some radii. The test `issue_143_stroke_and_fill` fails if the radius is changed to 4 pixel. I noticed this in the `fill-macros` example, which uses a 32 pixel radius, so maybe all even radii cause an issue.
