### ISSUE TITLE
Get style for `WithStyle` impls

### ISSUE THREAD

**Issue by jamwaffles** [jamwaffles/embedded-graphics#144]
There's no way to _get_ the style for elements that implement `WithStyle`. A `get_style()` (or similarly named) method should be added so the style properties can be retrieved.

I ran into this when attempting to toggle the border of an element on or off in a loop.

**Comment by rfuest** [comment]
Is this fixed now with the `Styled` refactor?

**Comment by jamwaffles** [comment]
Yeah I think so. The `PrimitiveStyle` and `TextStyle` fields are all `pub` as well so getting individual properties is also simple.
