### ISSUE TITLE
Mutating style API

### ISSUE THREAD

**Issue by jamwaffles** [jamwaffles/embedded-graphics#145]
As mentioned in https://github.com/jamwaffles/embedded-graphics/issues/139#issuecomment-515026696:

> This also raises another question about a mutating version of the style API, .... Probably a bunch of `*_mut()` methods...

**Comment by rfuest** [comment]
The `translate_mut` API change has it's own issue #211 now. Are there any additional mutable versions of APIs to discuss or can this be closed, because the style API changed?

**Comment by jamwaffles** [comment]
Not that I can think of. Closing...
