### ISSUE TITLE
BinaryColor -> u8 conversion

### ISSUE THREAD

**Issue by jamwaffles** [jamwaffles/embedded-graphics#151]
One for @rfuest:

The PR at jamwaffles/sh1106#9 raised a question which I can't remember if we discussed: should `impl From<BinaryColor> for u8` exist? It would be be a simple sugar that gets rid of the `match` in the linked PR and replaces it with a simple `pixel.1.into()`.

**Comment by rfuest** [comment]
I don't think it should. My rewrite of the image module contains a generic way of converting raw data into colors and back, which would get rid of the match. The code is almost ready for review, but depends on #148 being merged before.
