### ISSUE TITLE
Naming of stroke and fill color setters

### ISSUE THREAD

**Issue by rfuest** [jamwaffles/embedded-graphics#161]
I just noticed this bug introduced in the SH1106 driver recently: https://github.com/jamwaffles/sh1106/issues/10#issue-487632201

The contributor of that patch obviously didn't realize that the `with_stroke` method (now `stroke`) sets the color and not the width of the stroke. Should we change the name to `stroke_color` instead, to prevent this confusion in the future?

**Comment by jamwaffles** [comment]
Hm, yes that's probably a good idea. I think `.fill()` needs to become `.fill_color()` as well then, no?

**Comment by rfuest** [comment]
Yes, it should (see title :wink:).
