### ISSUE TITLE
Context API/retain chained object styling

### ISSUE THREAD

**Issue by jamwaffles** [jamwaffles/embedded-graphics#163]
Related to #162, #156 and styling in general, if a separate `Styled` struct is created as in #162, given the following chained iterator, how could it be styled?

```rust
let objects = Circle::new(icoord!(64, 64), 64)
    .into_iter()
    .chain(Line::new(icoord!(64, 64), icoord!(0, 64))))
    .chain(Line::new(icoord!(64, 64), icoord!(80, 80))))
    .chain(
        Font6x8::render_str("Hello World!")
            .translate(icoord!(5, 50)),
    );
```

Could each object's `IntoIterator` impl return a `Styled<Self, C>`? If so, then how would that work if no style has been explicitly set? `Styled::default()`?

**Comment by jamwaffles** [comment]
Can this be closed now? I think we've got a pretty good styling solution now.

**Comment by rfuest** [comment]
Yes we can close this.

Should I also close #149? I still like the way translation is handled by the context but it's outdated otherwise.

**Comment by jamwaffles** [comment]
Yeah I think both can be closed. There's the (poorly named) #211 which can probably take the discussion now.
