### ISSUE TITLE
Style::stroke_width type

### ISSUE THREAD

**Issue by rfuest** [jamwaffles/embedded-graphics#195]
`stroke_width` is currently stored as an `u8` which limits the stroke width to 255 pixels, which is less than the size of common displays like 320x240 LCDs. Most strokes are much smaller but IMO it should still be possible to set larger stoke sizes.

I would suggest to use an `u32` instead to be consistent with the `Size` type.

**Comment by jamwaffles** [comment]
That makes sense. I was wondering if it makes sense to shrink as many things as possible into `u16`s but that's probably a premature optimisation over `u32`.

**Comment by rfuest** [comment]
I did think about reducing the width of the coordinate types in the past to reduce memory consumption. But there might be benefits of having the additional bits for some applications.

Maybe this could be implemented as a feature to choose between the default 32 bit values and a reduced memory footprint 16 bit version.

Could you open another issue if you think that we should discuss this further?

**Comment by jamwaffles** [comment]
> Could you open another issue if you think that we should discuss this further?

I'll do this if/when Rust gets 8 bit AVR support, or if there's a lot of desire in the community for it I think. At that point, cramming things into `u16`s or `u8`s for space/perf will make a lot more sense.
