### ISSUE TITLE
New driver for ST7920 LCD controller

### ISSUE THREAD

**Issue by wjakobczyk** [jamwaffles/embedded-graphics#199]
Please list a new driver supporting embedded-graphics:
https://crates.io/crates/st7920

**Comment by jamwaffles** [comment]
Awesome! Would you be willing to PR this into `embedded-graphics/src/lib.rs` and `embedded-graphics/README.md`? If not I'll do the changes myself when I have a spare minute.

**Comment by wjakobczyk** [comment]
Sure, done.
https://github.com/jamwaffles/embedded-graphics/pull/200
