### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by rfuest** [jamwaffles/embedded-graphics#204]
Some changes made to the doc comments in `lib.rs` weren't also applied to `README.md`.

I would suggest to leave this issue open for now and check this before the `0.6` release.

**Comment by jamwaffles** [comment]
Is this related to #203 or is there something else in there that didn't get picked up?

**Comment by rfuest** [comment]
Not directly related to #203. But while looking at the new pretty picture I noticed some out of date information in the readme.
For example: The description of the `nalgebra` feature still uses `Coord` and `UnsignedCoord`.

**Comment by jamwaffles** [comment]
Ah I see. It would be great to either generate `README.md` from `lib.rs` (or vice versa) so these issues are less of a problem.
