### ISSUE TITLE
Builder for styles

### ISSUE THREAD

**Issue by rfuest** [jamwaffles/embedded-graphics#212]
Instances of styles are currently often created like this:
```rust
let decoration_style = PrimitiveStyle {
    fill_color: Some(BinaryColor::Off),
    stroke_color: Some(BinaryColor::On),
    stroke_width: 1,
};
```

One problem with this approach is that it isn't possible to add additional fields to the `PrimitityStyle` struct without breaking the user code. Using a builder pattern additional fields could be added without causing a breaking change.

**Comment by jamwaffles** [comment]
> One problem with this approach is that it isn't possible to add additional fields to the `PrimitityStyle` struct without breaking the user code.

Yeah I've been thinking that throughout the refactorings.

Do you have any thoughts on what the API should look like?

**Comment by rfuest** [comment]
> Do you have any thoughts on what the API should look like?

Not really, without taking a closer look at this first.

But I think it would be a good idea to prevent users from using the pattern in the first post by adding a private dummy field or making all fields private.

I would also like to keep `PrimitiveStyle::with_fill` and `PrimitiveStyle::with_stroke` and only require the builder for more complex styles.

**Comment by jamwaffles** [comment]
> But I think it would be a good idea to prevent users from using the pattern in the first post by adding a private dummy field or making all fields private.

A dummy field seems like a better bet (if a little more messy) as having the fields public is pretty handy for getting style properties IMO. 

> I would also like to keep PrimitiveStyle::with_fill and PrimitiveStyle::with_stroke and only require the builder for more complex styles.

That definitely makes sense, particularly if additional properties are added in the future.

**Comment by rfuest** [comment]
> A dummy field seems like a better bet (if a little more messy) as having the fields public is pretty handy for getting style properties IMO.

`#[non_exhaustive]` was just stabilized in `1.40.0`, which is much nicer that a dummy field: https://blog.rust-lang.org/2019/12/19/Rust-1.40.0.html#[non_exhaustive]-structs,-enums,-and-variants

**Comment by rfuest** [comment]
> Thoughts on requiring 1.40.0 as the MSRV?

I don't mind using the latest stable version as the MSRV in this early stage of e-g and the embedded ecosystem in general.

**Comment by jamwaffles** [comment]
Sweet, that's what I was thinking too. I only asked because I'm seeing a few more (non embedded) crates start specifying minimum versions.
