### ISSUE TITLE
Make lib.rs docs more complete

### ISSUE THREAD

**Issue by jamwaffles** [jamwaffles/embedded-graphics#236]
Taken from [this tweet](https://twitter.com/Rubberduck203/status/1212023503668551680):

> Speaking of. The docs on http://docs.rs don’t show how the `display` is initialized. I had to go to the project’s readme to find it.

The examples in `lib.rs` have the display initialisation lines hidden. The README has a `MockDisplay` created with a note instructing the reader to swap `MockDisplay` for their driver of choice. The lib.rs examples should do the same so the magic `display` variable doesn't just come from nowhere.

**Comment by rfuest** [comment]
On the topic of `MockDisplay`:
This is currently hidden from the docs, but used in the README. That is confusing for someone who tries to understand the examples and looks for it in the docs.
Should we make `MockDisplay` public? It could be useful for writing tests in other crates that depend on e-g.

**Comment by jamwaffles** [comment]
Sounds good to me 👍
