### ISSUE TITLE
Consuming builders for styles

### ISSUE THREAD

**Issue by rfuest** [jamwaffles/embedded-graphics#248]
`PrimitiveStyleBuilder` and `TextStyleBuilder` are currently implemented as "Non-consuming builders" (https://doc.rust-lang.org/1.0.0/style/ownership/builders.html). But it might be beneficial to change them to consuming builders.

Consuming builders can be used to generate `const`s, which would be pretty useful IMO. This won't be a advantage immediately, because trait bounds aren't yet supported for `const fn`s, but this way this won't be a breaking change later.

It could also generate more efficient code, because `build` doesn't need to `clone` the style anymore. (this is just an assumption and not tested)

Are there any advantages of leaving the builders as non-consuming variants?

**Comment by jamwaffles** [comment]
> Are there any advantages of leaving the builders as non-consuming variants?

I was going to type "giving multiple primitives the same style" but the code could of course just use the builder once and `.clone()` (or `Copy`) the resulting style. I can't think of any reason to make them non-consuming. I think it's a pretty common assumption that builders are of the consuming type anyway (citation needed) so that works out as well.

Should this go into 0.6.0 as a breaking change do you think?

**Comment by rfuest** [comment]
> I was going to type "giving multiple primitives the same style" but the code could of course just use the builder once and .clone() (or Copy) the resulting style.

I did also consider creating multiple similar styles as a possible advantage of the non consuming builder. But you can also `clone` the builder before calling `build` to reuse to builder.

> Should this go into 0.6.0 as a breaking change do you think?

Yes, they were only introduced in the latest alpha and not many projects will already use them, so I think it's best to change them now.

**Comment by jamwaffles** [comment]
Sounds good to me. I'll get a PR ready after #247 is merged. I cba with all the merge conflicts to do it in parallel :P
