### ISSUE TITLE
Add ellipse primitive

### ISSUE THREAD

**Issue by jamwaffles** [jamwaffles/embedded-graphics#283]
Similar to `Circle`, defined by top left as per #274, but with a width/height given as a `Size`. E.g.:

```rust
// Create an ellipse 10px wide, 20px tall
let ellipse = Ellipse::new(Point::zero(), Size::new(10, 20));

// Create a circle 20px in diameter
let ellipse = Ellipse::new(Point::zero(), Size::new(20, 20));
```

Questions:

1. [x] ~Should `Circle` become a simple wrapping struct to `Ellipse`, or should it be removed entirely? IMO `Circle` should be kept in.~ `Circle` will become a thin wrapper over `Ellipse`.

**Comment by rfuest** [comment]
> Should `Circle` become a simple wrapping struct to `Ellipse`, or should it be removed entirely? IMO `Circle` should be kept in.

I think I agree with that.

**Comment by jamwaffles** [comment]
Cool cool. Original comment updated.

**Comment by aurelj** [comment]
While this definition of an `Ellipse` covers pretty much all the common use cases, it should be noted that it doesn't allow drawing ellipses with their major and minor axis not horizontal and vertical.

I don't know if this case is worth supporting, but it is at least good to clearly know the limitations of the chosen definition.
