### ISSUE TITLE
Please make sdl dependency optional for the simulator

### ISSUE THREAD

**Issue by Boscop** [jamwaffles/embedded-graphics#294]
Thanks for this great crate. I'm using `embedded-graphics-simulator` to render data into ImageBuffers and then turn them into glium textures for use with imgui-rs.
But currently I get linking errors because I don't have SDL (and I don't want to have to link against SDL, to keep dependencies minimal).
Please make sdl an optional dependency for `embedded-graphics-simulator` :)

**Comment by jamwaffles** [comment]
Makes sense to me. Any thoughts @rfuest? I've opened #298 as a starting point.

**Comment by rfuest** [comment]
Using the simulator might not be the best option for @Boscop, as mentioned in https://github.com/jamwaffles/embedded-graphics/issues/299#issuecomment-605461098. But making SDL an optional dependency is a good idea anyway and would also help when using the simulator to generate PNGs in CI.
