### ISSUE TITLE
Line always has stroke width 1

### ISSUE THREAD

**Issue by Boscop** [jamwaffles/embedded-graphics#301]
No matter which value I pass to `.stroke_width()`, it always gets rendered as if the stroke width is 1. Any idea why?
```rust
Line::new(Point::new(x, 0), Point::new(x, h))
	.into_styled(
		PrimitiveStyleBuilder::new().stroke_color(Rgb888::new(255, 165, 0))
			.stroke_width(10).build()
	)
	.draw(&mut display)?;
```
![image](https://user-images.githubusercontent.com/535593/77830925-421e4080-712c-11ea-965e-e4843fbccc00.png)

**Comment by rfuest** [comment]
Thick lines aren't yet supported in e-g 0.6. But there is a PR #271 that will fix this soon.
