### ISSUE TITLE
Suggestion: Make PrimitiveStyle::with_fill/with_stroke const-fn

### ISSUE THREAD

**Issue by Boscop** [jamwaffles/embedded-graphics#303]
Is it possible to make these constructors const-fn?

**Comment by jamwaffles** [comment]
There might be some constructors that could be made const fn, yes, but any struct with a trait bound can't be made const on stable at the moment.

[This issue](https://github.com/rust-lang/rfcs/pull/2632) is the RFC for that feature.

**Comment by jamwaffles** [comment]
Closing as dupe of #205.
