### ISSUE TITLE
Some filled triangles cause endless loop

### ISSUE THREAD

**Issue by rfuest** [jamwaffles/embedded-graphics#308]
While preparing #307 I noticed a problem with some filled triangles:
```rust
Triangle::new(Point::new(10, 10), Point::new(20, 30), Point::new(30, -10))
    .into_styled(PrimitiveStyle::with_fill(BinaryColor::On))
    .draw(&mut display)?
```
Trying to execute this will cause an endless loop. The problem only occurs if a fill color is set.

**Comment by jamwaffles** [comment]
That ain't right. Lemme take a look.
