### ISSUE TITLE
New IBM437 font

### ISSUE THREAD

**Issue by sbechet** [jamwaffles/embedded-graphics#322]
- Version of embedded-graphics in use (if applicable): 0.6
- Target: N/A
- If using real hardware: N/A

## Description of the feature

Hello, new IBM437 font [crates](https://crates.io/crates/ibm437) today :-)

**Comment by rfuest** [comment]
Nice, now we can finally display some oldskool ASCII art.

Can you also open a PR to add the crate to `embedded-graphics/README.md` and `embedded-graphics/src/lib.rs`?

**Comment by sbechet** [comment]
done.
