### ISSUE TITLE
hello-world example in README.md is broken

### ISSUE THREAD

**Issue by rfuest** [jamwaffles/embedded-graphics#332]
The copy of the hello-world example in the readme is currently broken again.

Should we leave this issue open and fix this once before the release of the new stable version? Or should we reenable the readme check in master and comment the check out again before the release? Or is there a better permanent solution?

**Comment by jamwaffles** [comment]
Let's just leave this issue open for now, but I'd certainly like to find a better permanent solution.

**Comment by jamwaffles** [comment]
The `nalgebra_support` feature also has an outdated description:

```
- `nalgebra_support` - use the [Nalgebra](https://crates.io/crates/nalgebra) crate with `no_std`
  support to enable conversions from `nalgebra::Vector2` to `Coord` and `UnsignedCoord`.
```
