### ISSUE TITLE
Add ST7789 to supported list

### ISSUE THREAD

**Issue by almindor** [jamwaffles/embedded-graphics#347]
- Version of embedded-graphics in use (if applicable): `0.6.x`
- Target: real hardware
- If using real hardware: [ST7789](https://crates.io/crates/st7789)

Please link to the driver on <https://crates.io> if applicable.

## Description of the problem/feature request/other

Please add [ST7789](https://crates.io/crates/st7789) to the drivers that support embedded-graphics list.

**Comment by jamwaffles** [comment]
Added in #348, thanks!
