### ISSUE TITLE
ImageDimensions trait could use Size

### ISSUE THREAD

**Issue by rfuest** [jamwaffles/embedded-graphics#367]
The `ImageDimensions` trait contains a `width` and `height` getter which could be replaced by a single `size` getter. This would make it easier to use without having to manually create a `Size`.

@jamwaffles: Or was there any specific reason we didn't use `Size` in this case? `ImageDimensions` was introduced in #247 and just reused the same getters as the old `ImageFile` trait. So I guess we just didn't consider changing it and not that there is a specific reason to keep the separate getters.

**Comment by jamwaffles** [comment]
I think it should be pretty easy to remove `ImageDimensions` entirely. Is there a reason not to? I can take those changes on if you're not already working on it.
