### ISSUE TITLE
It's not obvious how you draw a bmp from `tinybmp` on the display

### ISSUE THREAD

**Issue by David-OConnor** [jamwaffles/embedded-graphics#372]
Eg:
```rust
let bmp = tinybmp::Bmp::from_slice(include_bytes!("../splash.bmp"))
    .expect("Failed to parse BMP image");

bmp.draw(disp);
```

**Comment by rfuest** [comment]
The `Bmp` object needs to be wrapped in an `Image` to specify the location it is drawn at. The `tinybmp` documentation contains and example how to draw an image using e-g: https://docs.rs/tinybmp/0.2.3/tinybmp/#integrate-with-embedded-graphics

**Comment by David-OConnor** [comment]
Awesome. That answers my question entirely.
