### ISSUE TITLE
TGA image example code in documentation doesn't compile

### ISSUE THREAD

**Issue by Thra11** [jamwaffles/embedded-graphics#374]
- Version of embedded-graphics in use: 0.6.2
- Version of tinytga in use: 0.3.2
- Target: simulator

## Description of the problem

This example code doesn't seem to compile for me: https://docs.rs/embedded-graphics/0.6.2/embedded_graphics/#display-a-tga-image . I get the following error:
```
error[E0308]: mismatched types
  --> src/main.rs:79:34
   |
79 |             let img = Image::new(&tga, Point::zero());
   |                                  ^^^^ expected struct `embedded_graphics::image::image_raw::ImageRaw`, found struct `tinytga::Tga`
   |
   = note: expected reference `&embedded_graphics::image::image_raw::ImageRaw<'_, _, _>`
              found reference `&tinytga::Tga<'_>`
```

**Comment by rfuest** [comment]
Did you enable the `embedded-graphics` feature for the `tinytga` crate?

**Comment by Thra11** [comment]
Thanks for the quick response! I did not enable the `embedded-graphics` feature. I have now. I still get the error.

**Comment by rfuest** [comment]
Sorry, I did make a mistake in my reply: The feature is called `graphics` and not `embedded-graphics`.

**Comment by Thra11** [comment]
Thanks! That fixed it. I wonder if adding a sentence to the example mentioning the `graphics` feature would help. Something like "tinytga must have the `graphics` feature enabled".

**Comment by rfuest** [comment]
> I wonder if adding a sentence to the example mentioning the `graphics` feature would help. Something like "tinytga must have the `graphics` feature enabled".

Yes, that's a good idea. I've opened an issue to keep track of this.

**Comment by Thra11** [comment]
Thanks. I'll close this one.
