### ISSUE TITLE
Simulator example in README uses different size than stated

### ISSUE THREAD

**Issue by bugadani** [jamwaffles/embedded-graphics#385]
The simulator README [here](https://github.com/jamwaffles/embedded-graphics/blame/master/simulator/README.md#L13) reads "Simulate a 128x64 SSD1306 OLED", but then the example code uses `Size::new(129, 129)` [here](https://github.com/jamwaffles/embedded-graphics/blame/master/simulator/README.md#L26)

**Comment by jamwaffles** [comment]
This was fixed in #381 I believe.
