### ISSUE TITLE
Replace scripts with the `just` task runner

### ISSUE THREAD

**Issue by rfuest** [jamwaffles/embedded-graphics#394]
e-g contains multiple scripts to generate files or to aid with CI. This collection of scripts isn't very well documented and the required parameters aren't obvious.

I would suggest to replace the scripts be using a task runner like [casey/just](https://github.com/casey/just/) or [sagiegurari/cargo-make](https://github.com/sagiegurari/cargo-make). This way all task can be defined and documented in one central file and we can also benefit from other features like dependencies between tasks.

**Comment by jamwaffles** [comment]
> e-g contains multiple scripts to generate files or to aid with CI. This collection of scripts isn't very well documented and the required parameters aren't obvious.

I agree. Thanks for opening this issue.

I had a quick look at both of those linked projects and I'm leaning towards `just` over `cargo-make`. I like the idea of TOML command files, but the syntax is pretty verbose. `just` uses a custom file format, but doesn't look too complex as I think what we kind of want is "bash, but just a little bit more". Do you have a preference/reason not to use `just`?

**Comment by rfuest** [comment]
No, I'm using `just` in another project and I really like it. It's focused on one task and doesn't try to be a solution for everything. The syntax is similar to a Makefile without some of the weirdness.

**Comment by jamwaffles** [comment]
Alright, let's go with `just` then :). If you want to take this on please assign yourself to the issue so I don't step on your toes.
