### ISSUE TITLE
Dimensions for styled primitives don't use stroke width and alignment

### ISSUE THREAD

**Issue by rfuest** [jamwaffles/embedded-graphics#428]
The `Dimensions` impl for styled primitives returns the same dimensions as the base primitive, but the actual dimensions could be larger if the stroke alignment is set to `Outside` or `Center` and the stroke width is non zero.

**Comment by jamwaffles** [comment]
I think I ran into this when attempting to fix #405 so would indeed be good to solve for all primitives.
