### ISSUE TITLE
Rectangle intersection logic incorrect

### ISSUE THREAD

**Issue by vinaychandra** [jamwaffles/embedded-graphics#452]
- Version of embedded-graphics in use (if applicable): [version here] master
- Target: [simulator] / [real hardware] any
- If using real hardware: [display driver used]

Please link to the driver on <https://crates.io> if applicable.

## Description of the problem/feature request/other

[description here]
The current intersection logic in [master](https://github.com/jamwaffles/embedded-graphics/blob/master/embedded-graphics/src/primitives/rectangle/mod.rs#L211) is this

```
				// Check for overlap
                if self.contains(other.top_left)
                    || self.contains(other_bottom_right)
                    || other.contains(self.top_left)
                    || other.contains(self_bottom_right)
```
This fails in case where self is (0, 100) - (100, 600) and other is (50, 50) - (150, 15) but there is a clear intersection of the Rectangle (50, 100) - (100, 150)

Also, following rust paradigms, intersection should probably return an `Option` rather than `zero` rectangle as the result.

**Comment by jamwaffles** [comment]
Thanks for the bug report. I'll reproduce and get a fix ready when I have some spare time. PRs also accepted ;)
