### ISSUE TITLE
Primitives are missing pixels?

### ISSUE THREAD

**Issue by therealprof** [jamwaffles/embedded-graphics#5]
Maybe it's just me but the triangle and the rectangle from the graphics example in the `SSD1306` crate seem to be missing a pixel each in the lower right corner.

**Comment by jamwaffles** [comment]
Ah no they are! I keep meaning to open an issue for this so thanks for doing it for me. I'll have a look at this now.

**Comment by jamwaffles** [comment]
It's late and I'm knackered but I think this is fixed by a52f8a86215c3606a73f6321359a014d07d7f3c4 and 1e3d86cb342fb296b9644a0daca10599a908d51d. let me know if you have any more problems.

**Comment by therealprof** [comment]
Looks good.
