### ISSUE TITLE
Question: Add some basic Enums/Traits for all Displays to this crate?

### ISSUE THREAD

**Issue by Caemor** [jamwaffles/embedded-graphics#50]
For example the DisplayRotation-Enum (https://jamwaffles.github.io/ssd1306/master/ssd1306/displayrotation/enum.DisplayRotation.html) is gonna be implemented by many of the consumers of this crate. Would it be useful to directly add this here or is that too much off-topic?

**Comment by jamwaffles** [comment]
I think that's out of scope for this crate. Embedded_graphics should be a layer that sits on top of any hardware abstraction so drawing can be performed on anything from an SSD1306 to a Vulkan texture (for example) using the same code. I think display rotation is up to the display driver to implement, not embedded_graphics. There may be place for a set of display traits, but I don't think this crate is it :slightly_smiling_face:
