### ISSUE TITLE
Infinite font iterator when negative translation happens to be the font height

### ISSUE THREAD

**Issue by MabezDev** [jamwaffles/embedded-graphics#81]
I've run into an issue where the fontbuilder iterator will loop indefinitely under certain translation conditions.

Here's a minimal example:
```        
display.draw(Font6x12::render_str("Testing string")
            .with_stroke(Some(0xF1FA_u16.into()))
            .translate(Coord::new(0, -12))
            .into_iter());
display.flush();
```

if a negative `y` translation happens to be equal to the height of the font, it will loop indefinitely in here: https://github.com/jamwaffles/embedded-graphics/blob/master/embedded-graphics/src/fonts/font_builder.rs#L193

**Comment by jamwaffles** [comment]
Ouch, thanks for debugging and reporting this. I'm pretty busy at the moment but I'll get a fix in when I can. PRs welcome if you want to accelerate the fix :slightly_smiling_face:
