### ISSUE TITLE
PixelColor types

### ISSUE THREAD

**Issue by rfuest** [jamwaffles/embedded-graphics#89]
The `PixelColor` trait is implemented for both `PixelColorUx` and `ux` (with x = 8, 16, 32). Why are the `PixelColorUx` types used instead of the unwrapped variants?

The `PixelColorUx` types don't seem to add any additional semantic information. Maybe it would be beneficial to add predefined types for commonly used pixel formats, like a newtype for RGB565 or an enum for 1 bpp displays.

**Comment by jamwaffles** [comment]
Hmm, I can't remember my reasoning at the time. I'm sure it had good intentions but yes, they seem rather redundant now. Newtypes for different pixel formats are a much better idea, thanks for the suggestion!
